name: Tests (Linux, Python 3.8)

on:
  workflow_call:

jobs:
  test-linux-38:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: make dev
          
      - name: Run tests
        run: make tests
